### ISSUE TITLE
Missing ./clean.sh script

### ISSUE THREAD

**Issue by erickisos** [pfavr2/install_ros2_rolling_on_mac_m1#1]
Hey!

I just saw your answer in ROS discourse and after a quick read of your script I tried to run it by myself, I had to stop the execution due to a missing step and now I'm getting a failure asking to execute the clean.sh script, which is not in the repository, I'll manually delete the created dirs and other files referenced by your script but wanted to know if you already have that file, otherwise I can write one and submit a PR with my findings.

**Comment by pfavr2** [comment]
Thank you for the feedback. I forgot to add the script, sorry I'll correct that in a minute.

What was the missing step you experienced?

**Comment by pfavr2** [comment]
clean.sh script has been added.

**Comment by erickisos** [comment]
Cool! I forgot to accept the xcode license hahaha, so I stopped the process and then realized that I can't restart, I just deleted manually the main dir, but keep looking on your test, if I see something misbehaving will let you know, thanks for the support.

**Comment by pfavr2** [comment]
Thank you, I hope to be able to make the patches a bit nicer and then push the changes upstream to the individual packages. When they are accepted they can be removed from this project and voila: Mac M1 will be supported in ROS2 also 😀

Please let me know if you experience any issues.

Best regards,

Peter
