### ISSUE TITLE
deprecated global-option in latest pip

### ISSUE THREAD

**Issue by makeecat** [pfavr2/install_ros2_rolling_on_mac_m1#3]
The latest pip deprecate the global option, in order to use that, we should use:

```pip install --config-settings="--global-option=build_ext" --config-settings="--global-option=-I/opt/homebrew/opt/graphviz/include/" --config-settings="--global-option=-L/opt/homebrew/opt/graphviz/lib/" pygraphviz```

This solution has been validated in M1 with macOS 14.0 (23A344)

**Comment by pfavr2** [comment]
Thank you for this contribution. Much appreciated!
