### ISSUE TITLE
Failure to Build ROS

### ISSUE THREAD

**Issue by Relmnicoder** [pfavr2/install_ros2_rolling_on_mac_m1#5]
Hello! 

While running the install script at some point one third way through building ROS, it fails at `builtin_interfaces`.

Specifically the error is:

```
--- stderr: builtin_interfaces
CMake Error at /opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonExtra (missing: PythonExtra_LIBRARIES)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.28.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/ros/ros2_rolling/install/python_cmake_module/share/python_cmake_module/cmake/Modules/FindPythonExtra.cmake:224 (find_package_handle_standard_args)
  /opt/ros/ros2_rolling/install/rosidl_generator_py/share/rosidl_generator_py/cmake/rosidl_generator_py_generate_interfaces.cmake:23 (find_package)
  /opt/ros/ros2_rolling/install/ament_cmake_core/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:48 (include)
  /opt/ros/ros2_rolling/install/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:280 (ament_execute_extensions)
  CMakeLists.txt:19 (rosidl_generate_interfaces)


---
Failed   <<< builtin_interfaces [25.5s, exited with code 1]
Aborted  <<< unique_identifier_msgs [25.5s]
Aborted  <<< rviz_ogre_vendor [6min 25s]

Summary: 153 packages finished [7min 31s]
  1 package failed: builtin_interfaces
  2 packages aborted: rviz_ogre_vendor unique_identifier_msgs
  21 packages had stderr output: builtin_interfaces cyclonedds fastcdr foonathan_memory_vendor gmock_vendor google_benchmark_vendor gtest_vendor iceoryx_binding_c iceoryx_hoofs iceoryx_introspection iceoryx_posh rcl_logging_interface rcutils rmw rti_connext_dds_cmake_module rttest rviz_ogre_vendor tlsf uncrustify_vendor unique_identifier_msgs urdfdom_headers
  178 packages not processed
 ```

I assume PythonExtra is a C++ library, maybe the python headers? But I struggle to find any other information about it.
And I thought brew installed python with headers.

My Python version is `3.11.6` and brew is up to date.

Apologies but could you help me with this?

**Comment by pfavr2** [comment]
Hi,

Thank you for creating an issue and the good report of the build fail you experience 👍 

Maybe it is related to a brew package you have installed, please do:

brew list | grep -i python

and share the output?

On my machine it gives these packages:
boost-python3
python-packaging
python-ply
python-pyparsing
python-setuptools
python@3.11

I also just found some other issues while building. I'm trying to fix these and will then commit an update to this repository.

Best regards,

Peter

**Comment by Relmnicoder** [comment]
output of brew list | grep -i python: 

```
python-certifi
python-markupsafe
python-packaging
python-ply
python-setuptools
python-tabulate
python@3.11
```

I just installed boost-python3 but it installs a python@3.12 version which I think creates the same problem as with having openCV installed as with the other issue. 

Also thank you for taking your time. I really appreciate it! :D

**Comment by pfavr2** [comment]
If you want to remove python@3.12 without removing dependencies (just while building ros2):

brew uninstall --ignore-dependencies python@3.12

**Comment by pfavr2** [comment]
I have just pushed some changes. Waiting for the build to finish here... (so can't say for sure it builds all 334 packages)....

**Comment by pfavr2** [comment]
Now it works here on my M2 macbook:

Summary: 334 packages finished [14min 58s]

**Comment by Relmnicoder** [comment]
Hm, So I installed the same python packages that you have, and yet still run into not finding PythonExtra.

My MacOS version is Sonoma 14.2

and my xcode version from `xcodebuild -version` is `Xcode 15.1 Build version 15C65`

**Comment by pfavr2** [comment]
Sonoma 14.2.1 (23C71)
Maybe it is some additional packages you have installed?

Please try ./clean.sh before ./install.sh (if not done already)?

Here is my "brew list | sort":

`
abseil
adwaita-icon-theme
aften
alt-tab
antlr
antlr4-cpp-runtime
aom
aribb24
asio
assimp
at-spi2-core
atk
berkeley-db
bison
boost
boost-python3
brotli
bullet
c-ares
ca-certificates
cairo
capstone
cargo-c
ceres-solver
cjson
clipy
cmake
console_bridge
cpio
cppcheck
cunit
curl
dav1d
dbus
dnsmasq
dotnet@6
double-conversion
dtc
eigen
emacs
faac
faad2
fdk-aac
ffmpeg
ffmpeg@4
flac
fmt
fontconfig
foxglove-studio
freecad
freetype
frei0r
fribidi
gcc
gd
gdk-pixbuf
gettext
gflags
ghostscript
giflib
git-lfs
gl2ps
glew
glib
glib-networking
glog
gmp
gnu-getopt
gnu-sed
gnutls
gobject-introspection
graphene
graphite2
graphviz
grep
gsettings-desktop-schemas
gstreamer
gtk+3
gtk-vnc
gtk4
gtksourceview4
gts
harfbuzz
hdf5
hicolor-icon-theme
highway
hunspell
hwloc
icu4c
imagemagick
imath
isl
jack
jansson
jasper
jbig2dec
jpeg-turbo
jpeg-xl
json-glib
jsoncpp
lame
leptonica
libaec
libarchive
libass
libavif
libb2
libbluray
libcuefile
libde265
libepoxy
libevent
libgcrypt
libgit2
libgpg-error
libheif
libidn
libidn2
libiscsi
liblqr
libmaxminddb
libmicrohttpd
libmng
libmpc
libnghttp2
libogg
libomp
libosinfo
libpng
libpsl
libpthread-stubs
libraw
libreplaygain
librist
librsvg
libsamplerate
libshout
libslirp
libsmi
libsndfile
libsodium
libsoup
libsoxr
libssh
libssh2
libtasn1
libtiff
libtool
libunibreak
libunistring
libusb
libusrsctp
libuv
libvidstab
libvmaf
libvorbis
libvpx
libwebsockets
libx11
libxau
libxcb
libxdmcp
libxext
libxfixes
libxi
libxml2
libxrender
libxtst
little-cms2
llvm
lua
lz4
lzo
m4
mbedtls
mcap
md4c
meson
metis
mosquitto
mpdecimal
mpfr
mpg123
musepack
nasm
ncurses
netcdf
netpbm
nettle
ninja
notunes
numpy
openblas
opencore-amr
opencv
openexr
openjdk
openjpeg
openldap
openssl@3
openvino
opus
orc
orocos-kdl
osinfo-db
pango
pcre
pcre2
pixman
pkg-config
poco
protobuf
protobuf@3
pugixml
py3cairo
pygobject3
pyqt
pyqt-builder
pyqt@5
python-packaging
python-ply
python-pyparsing
python-setuptools
python@3.11
qemu
qt
qt@5
rar
rav1e
readline
rtmpdump
rubberband
rust
sdl2
shared-mime-info
sip
snappy
spdlog
speex
speexdsp
spice-gtk
spice-protocol
sqlite
srt
srtp
suite-sparse
svt-av1
taglib
tbb
tesseract
theora
tinyxml
tinyxml2
tree-sitter
unbound
usb.ids
usbredir
utf8cpp
vde
vte3
vtk
webp
wget
wireshark
x264
x265
xorgproto
xvid
xz
yajl
yasm
z3
zeromq
zimg
zstd`

**Comment by pfavr2** [comment]
Hi @Relmnicoder,

I'm going to close this issue as it builds perfectly on my machine and you haven't replied to the above.

Please let me know if you succeeded building or still have problems - I'll be happy to try to help fixing it.

Best regards,

Peter

**Comment by Relmnicoder** [comment]
Hey @pfavr2!

Thanks for all the help! 
So It seems I had installed something else which was causing the library to not be found. 
I found out after installing all brew packages of yours that I didn't already have, and the problem still persisted.
Then I started to go through my installs and started to delete a lot of things, in big swaths and one of them was the problem cause.

I am going to try to figure out what it maybe was and give a short last update, but it seems to be working now. Thank you!!! <3

**Comment by Relmnicoder** [comment]
So I reinstalled everything that I had de installed, and I still seem to be able to build it after cleaning and installing it again. So in the end I don't really know what went wrong? It's a bit (very) frustrating to lose so much time on something that seems to be not reproduce able. 

But either way Thank you very much for the help.

**Comment by pfavr2** [comment]
@Relmnicoder  thank you for the feedback. Good to hear it is working now 👍
