### ISSUE TITLE
Asks for patch file

### ISSUE THREAD

**Issue by KostyalBalint** [pfavr2/install_ros2_rolling_on_mac_m1#8]
After running the `install.sh` script it successfully installs a lot of things with homebrew, but when starting to apply patches at line 120 it stops and asks for files to patch: 
```bash
no such option: --config-settings
Requirement already satisfied: pip in ./python_venv/lib/python3.9/site-packages (21.2.4)
Collecting pip
  Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-24.0
File to patch:
```
and waits for user input

This is the line in the install.sh file. 
```
120: patch < "$SCRIPT_DIR/patches/python_setuptools_easy_install.patch"
````

What am I doing wrong?

**Comment by pfavr2** [comment]
Thanks @KostyalBalint for the report!

I'm currently investigating :-)

**Comment by pfavr2** [comment]
I think it is something with the python version.

**Comment by KostyalBalint** [comment]
Here in the install step I changed python to python@3.11 because by default it installed 3.12, which as stated in #4 is not supported. The new install looks like this:

```
###################################
# Installing ROS2 dependencies
###################################
brew install asio assimp bison bullet cmake console_bridge cppcheck \
  cunit eigen freetype graphviz opencv openssl orocos-kdl pcre poco \
  pyqt5 python@3.11 qt@5 sip spdlog tinyxml tinyxml2
  
  ```

**Comment by pfavr2** [comment]
Thank you @KostyalBalint !

I have included it and now it works again 😀
